### ISSUE TITLE
email send only to one user

### ISSUE THREAD

**Issue by CEHT9I6Pb** [eckucukoglu/redmine-reminder-emails#9]
script send email only to one user from all list users.

what i can check?

![default](https://cloud.githubusercontent.com/assets/14824292/18515674/50523726-7ac0-11e6-922a-6e4088705589.png)

**Comment by eckucukoglu** [comment]
hi @CEHT9I6Pb,

First of all, I couldn't understand your screenshot, is it from other script or did you stylize this plugin?

This plugin offers a task that sends reminder emails about **assigned and active issues** that are past due or due in the next specified number of days. Therefore, I guess, in your situation only 1 user has tasks that active&assigned to this user.

I have tested again anyway in case of your claim is true, however it seems work w/o any problems if more than one user have tasks that active&assigned to these users. 

If any user has not any issues that 
1. assigned to him AND 
2. active AND
3. past due or due in the next specified number of days

then user should not receive mails. It's an expected behaviour of this plugin.

Could you please give me more details, logs and content of your script that plugin created.

**Comment by CEHT9I6Pb** [comment]
hi,
in first - sorry for my english :(

in screenshot list of users in test project, in project many issues open more then 1 days ago.
in console i send command:
>  bundle exec rake redmine:send_reminders project="34" days=1 RAILS_ENV="production"
or 
> /usr/local/rvm/gems/ruby-2.3.0/bin/rake redmine:send_reminders project="34" days="1" RAILS_ENV="production"

and email transmit only to one user from list. screenshot with open active issues project 34 in attach 
![2](https://cloud.githubusercontent.com/assets/14824292/18536971/27e9114e-7b2c-11e6-8fde-7c10a0001e6c.png)

**Comment by CEHT9I6Pb** [comment]
sorry, my error. not carefully read description :(

**Comment by eckucukoglu** [comment]
np :)
